name: Deploy to Azure SQL Database
on:

  push:
    branches:
       -  master
       -  prod
       -  preprod
  # pull_request:
  #   branches: [ master ]      
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    # - name: Build Database project
    #   run: |
    #     # cd AdventureWorks2012
    #     msbuild.exe AdventureWorks2012.sln --output ${{github.workspace}}/myapp
      
    # - uses: actions/upload-artifact@v3.0.0
    #   with:
    #      name: SQLDB
    #      path: ${{ github.workspace }}/myapp      

         
    - name: Build Database project
      run: |
        # cd AdventureWorks2012
        msbuild.exe AdventureWorks2012.sln /p:Configuration=Release

         
    - uses: actions/upload-artifact@v3.0.0
      with:
         name: SQLDB
         path: ${{ github.workspace }}/AdventureWorks2012/bin/Release/

  DeploySQLDBToDev:
    runs-on: windows-latest
    needs: build
    # if: success() && github.ref == 'refs/heads/preprod'
    # if: github.event.ref == 'refs/heads/test' && success()
    # if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'master'
    # if: github.event.ref == 'refs/heads/master' && success()
    # if: github.event.ref == 'refs/heads/devbranch' && success()
    # environment: ${{ github.ref == 'refs/heads/master' ? 'production' : 'staging' }}
    environment: DeploySQLDB

    steps:
       - name: download artifact contaning dacpac
         uses: actions/download-artifact@v3.0.0
         with:
            name: SQLDB

       # - uses: azure/login@v1
       #   with: 
       #     creds: ${{ secrets.AZURE_CREDENTIALS }}
           
       - uses: azure/login@v1
         with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

       # - name: Fetch secrets from Azure Key Vault
       #   id: keyvault
       #   uses: azure/get-keyvault-secrets@v1
       #   with:
       #     keyvault: ${{ secrets.KEYVAULT_NAME }}
       #     secrets: |
       #      connectionStrin
            
       - name: Azure SQl deploy-database
         uses: azure/sql-action@v2.3
         with:
           connection-string: Server=tcp:testdbserver901.database.windows.net,1433;Initial Catalog=testdb;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;Authentication="Active Directory Default";
          # connection-string: ${{ steps.keyvault.outputs.connectionStrin }}
           path: .SQLDB/AdventureWorks2012.dacpac
           # dacpac-package: 'AdventureWorks2012.dacpac'

  # DeploySQLDBToPrd:
  #   runs-on: windows-latest
  #   needs: DeploySQLDBToDev
  #   if: success() && github.ref == 'refs/heads/prod'
  #   environment: DeploySQLDBProd
  #   steps:
  #      - name: download artifact contaning dacpac
  #        uses: actions/download-artifact@v3.0.0
  #        with:
  #           name: SQLDB

       # - uses: azure/login@v1
       #   with: 
       #     creds: ${{ secrets.AZURE_CREDENTIALS }}
           
       # - uses: azure/login@v1
       #   with:
       #    client-id: ${{ secrets.AZURE_CLIENT_ID }}
       #    tenant-id: ${{ secrets.AZURE_TENANT_ID }}
       #    subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

       # - name: Azure SQl deploy 
       #   uses: Azure/sql-action@v1.3
       #   with:
       #     server-name: advtestsqldb001.database.windows.net
       #     connection-string: '${{ secrets.AZURE_SQL_CONNECTION_STRING_PRD }}'
       #     dacpac-package: 'AdventureWorks2012.dacpac'   
    
  
    # - name: Deploy DACPAC to Azure SQL Database
    #   uses: azure/sql-action@v1
    #   with:
    #     server-name: advtestsqldb001.database.windows.net  # Update this
    #     connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
    #     dacpac-package: './output/AdventureWorks2012.dacpac'
    #     # Update the path to your DACPAC
